source: 
    path: "sourcePath"
    pattern: "*.wav"

destination: 
    path: "destinationPath"
    extension: ".sln"
    purge: None

command:
    template: 'ffmpeg -i "{inputFile}" -ar 8000 -ac 1 -acodec pcm_s161e -f s161e "{outputFile}"'
